name: Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install pytest
          python -m pip install markdown-link-check
      - name: Run tests
        run: |
          if [ -d "tests" ]; then
            python -m pytest tests/
          fi
      - name: Check for required files and directories
        run: |
          if [ ! -d "docs" ]; then
            echo "Directory 'docs' is missing"
            exit 1
          fi
          if [ ! -d "examples" ]; then
            echo "Directory 'examples' is missing"
            exit 1
          fi
          if [ ! -d "libs" ]; then
            echo "Directory 'libs' is missing"
            exit 1
          fi
          if [ ! -f "__init__.py" ]; then
            echo "File '__init__.py' is missing"
            exit 1
          fi
          if [ ! -f "package.json" ]; then
            echo "File 'package.json' is missing"
            exit 1
          fi
          if [ ! -f "README.md" ]; then
            echo "File 'README.md' is missing"
            exit 1
          fi
      - name: Check if README.md check is required
        if: ${{ github.event.pull_request.head.commit.message }} =~ "check-readme"
        run: |
          # Check if README.md has been updated
          uses: marketplace/actions/diff-so-fancy@v1.1
          with:
            base: qa
            head: ${{ github.event.pull_request.head.sha }}
            file: README.md
      - name: Approve pull request
        if: success()
        uses: peter-evans/create-pull-request-review@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: APPROVE
      - name: Reject pull request
        if: failure()
        uses: peter-evans/create-pull-request-review@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: REQUEST_CHANGES
          body: |
            Please make sure that the following requirements are met:
            - The repository has a 'docs' directory
            - The repository has an 'examples' directory
            - The repository has a 'libs' directory
            - The repository has an '__init__.py' file
            - The repository has a 'package.json' file
            - The repository has a 'README.md' file
            - If specified in the commit message, the 'README.md' file has been updated